-- Creates property spatial view - Joins parcels to replicated NCS property tables
USE [GIS_Vector_Core]
GO

CREATE view gisadmin.vwProperty as SELECT gisadmin.Parcel.OBJECTID, gisadmin.Parcel.Shape, gisadmin.NCSRAPROPERTY.valuation_id AS Valuation_ID, CAST(gisadmin.NCSRAPROPERTY.ra_unique_id AS bigint) AS Property_Number, gisadmin.NCSRAPEOPLE.ratepayer_name_1 AS Ratepayer_Name1, gisadmin.NCSRAPEOPLE.ratepayer_name_2 AS Ratepayer_Name2, gisadmin.NCSRAPEOPLE.ratepayer_address_1 AS Ratepayer_Address1, gisadmin.NCSRAPEOPLE.ratepayer_address_2 AS Ratepayer_Address2, gisadmin.NCSRAPEOPLE.ratepayer_address_3 AS Ratepayer_Address3, gisadmin.NCSRAPEOPLE.ratepayer_address_4 AS Ratepayer_Address4, gisadmin.NCSRAPEOPLE.owner_name_1 AS Owner_Name1, gisadmin.NCSRAPEOPLE.owner_name_2 AS Owner_Name2, gisadmin.NCSRAPEOPLE.owner_address_1 AS Owner_Address1, gisadmin.NCSRAPEOPLE.owner_address_2 AS Owner_Address2, gisadmin.NCSRAPEOPLE.owner_address_3 AS Owner_Address3, gisadmin.NCSRAPEOPLE.letter_name_1 AS Letter_Name1, gisadmin.NCSRAPEOPLE.letter_name_2 AS Letter_Name2, gisadmin.NCSRAPROPERTY.improvements AS Improvements, gisadmin.NCSRAPROPERTY.certificate_of_title AS Certificate_Of_Title, gisadmin.NCSRAPROPERTY.legal_description AS Legal, gisadmin.NCSRAPROPERTY.house_no AS House_No, gisadmin.NCSRASTREET.address_1 AS Address_1, gisadmin.NCSRASTREET.address_2 AS Address_2, CAST(CASE WHEN gisadmin.NCSRAVALUATION.valuation_date = 'None' Then NULL ELSE gisadmin.NCSRAVALUATION.valuation_date END AS CHAR) AS Valuation_Date, CAST(gisadmin.NCSRAVALUATION.land_value AS FLOAT) AS Land_Value, CAST(gisadmin.NCSRAVALUATION.capital_value AS FLOAT) AS Capital_Value, CAST(gisadmin.NCSRAVALUATION.capital_value AS FLOAT) - CAST(gisadmin.NCSRAVALUATION.land_value  AS FLOAT) AS Improvements_Value, CAST(gisadmin.NCSRAVALUATION.hectares AS FLOAT) AS Hectares, CAST(gisadmin.NCSRAVALUATION.last_sale_price AS FLOAT) AS Last_Sale_Price, CAST(CASE WHEN gisadmin.NCSRAVALUATION.last_sale_date = 'None' Then NULL ELSE gisadmin.NCSRAVALUATION.last_sale_date END AS CHAR) AS Last_Sale_Date, CAST(gisadmin.NCSRAFINANCIAL.total_rates_for_this_year AS FLOAT) AS Total_Rates_For_This_Year, CAST(gisadmin.NCSRAFINANCIAL.total_balance_owing AS FLOAT) AS Rates_To_Clear, (CAST(gisadmin.NCSRAFINANCIAL.total_rates_for_this_year  AS FLOAT) * 3) / 23 AS GST_on_This_Year_Rate, CAST(gisadmin.NCSRAVALUATION.new_capital_value AS FLOAT) - CAST(gisadmin.NCSRAVALUATION.new_land_value AS FLOAT) AS New_Improvements_Value, gisadmin.NCSRAPROPERTY.new_legal_description AS NLegal, CAST(gisadmin.NCSRAVALUATION.new_land_value AS FLOAT) AS New_Land_Value, CAST(gisadmin.NCSRAVALUATION.new_capital_value AS FLOAT) AS New_Capital_Value, gisadmin.NCSRAPROPERTY.new_improvements AS New_Improvements, CAST(gisadmin.NCSRAVALUATION.new_hectares AS FLOAT) AS New_Hectares  

FROM gisadmin.NCSRGPROPERTYRECORD RIGHT JOIN ((gisadmin.NCSRAVALUATION RIGHT JOIN ((gisadmin.NCSRAPROPERTY LEFT JOIN gisadmin.NCSRAFINANCIAL ON gisadmin.NCSRAPROPERTY.ra_unique_id = gisadmin.NCSRAFINANCIAL.ra_unique_id) INNER JOIN gisadmin.NCSRASTREET ON gisadmin.NCSRAPROPERTY.street_id = gisadmin.NCSRASTREET.street_id) ON gisadmin.NCSRAVALUATION.ra_unique_id = gisadmin.NCSRAPROPERTY.ra_unique_id) INNER JOIN gisadmin.NCSRAPEOPLE ON gisadmin.NCSRAPROPERTY.ra_unique_id = gisadmin.NCSRAPEOPLE.ra_unique_id) ON gisadmin.NCSRGPROPERTYRECORD.ra_unique_id = gisadmin.NCSRAPROPERTY.ra_unique_id
JOIN gisadmin.Parcel
ON gisadmin.NCSRGPROPERTYRECORD.upi_id = gisadmin.Parcel.PAR_ID
GO


